### ISSUE TITLE
Succeeding add-on for dexterity?

### ISSUE THREAD

**Issue by ksuess** [collective/Products.PloneGlossary#8]
Anybody already working on a succeeding glossary add-on with tooltips for dexterity?

**Comment by mauritsvanrees** [comment]
Old question, you know the answer by now: you yourself have been working on [`collective.glossary`](https://github.com/collective/collective.glossary). :-)

Just checking if I understand the distinctions correctly myself.

`Products.PloneGlossary`:

- The tool is built on Archetypes: the `PloneGlossary` and `PloneGlossaryDefinition` portal types are Archetypes.
- It can find and highlight search terms in both Archetypes and Dexterity.

`collective.glossary`:

- The tool is built on Dexterity: its portal types are Dexterity content types.
- It can only find and highlight search terms in Dexterity items.  This is a guess really, but I don't see Archetypes mentioned in the repo.
